# Generated by Django 4.2.11 on 2024-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pics'),
        ),
    ]
