# Generated by Django 4.2.11 on 2024-10-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatroom_name_remove_chatroom_user1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_media/'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('gif', 'GIF'), ('video', 'Video')], default='text', max_length=10),
        ),
    ]
