# Generated by Django 4.2.11 on 2024-10-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_options_message_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
