services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: socialmediapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rahulrj@97
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    restart: always

  backend:
    build:
      context: ./socialapp    # Updated to point to the correct Dockerfile location
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 socialapp.asgi:application"
    volumes:
      - ./socialapp:/app       # Updated to map the Django project code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECRET_KEY=django-insecure-qc^nta&e!2azfatkv@lhtrak=yqa1c=vp4l-0v=tfbccw6krhr
      - DB_HOST=db
      - DB_PORT=5432
    working_dir: /app          # Updated working directory
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./socialapp/static:/static
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
